### ISSUE TITLE
As Dataprovider I want to have the option to order datapackages

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3150]
As a logged in dataprovider I'm currently not able to order datapackages since the GUI only provides the cockpit view. Having the future implementation of SSO in mind, logged in data provider should also be able to order data packages. In order to keep the different functional areas separate, we need a dialog in the MDM in which it is possible to switch between the views for searching (ordering) and the view for submitting (meta)data when users are logged in.  This is to be done via two prominent buttons in the header bar (see mock-up 1). 

Button 1
de: "Daten übergeben"; en: "Provide Data"

Button 2
de: "Daten bestellen"; en: "Order data" 

mock-up1 Cockpit view for submitting (meta)data (data submission view)
![grafik](https://user-images.githubusercontent.com/17981185/202483445-40418ae2-0903-4504-9d9b-79e7e3e2e1fd.png)

mock-up2 View for searching and ordering data (order view)
![grafik](https://user-images.githubusercontent.com/17981185/202483795-62eef1b8-77e4-4654-84d6-d61369899802.png)

The standard view after log in should be the order view. 

When a logged in person clicks on the "Provide Data" button, it should be checked if the account is assigned to a data provision project. If not, a notification should be displayed:

de: "Ihnen ist derzeit kein Datenübergabeprojekt zugewiesen, bitte kontaktieren Sie das FDZ-DZHW über datadesposit@dzhw.eu, um die weiteren Details der Übergabe zu klären" 

en: "You are currently not assigned to a data provision project, please contact the FDZ-DZHW via datadesposit@dzhw.eu to clarify the further details of the data provision"

If the account is assigned to a data provision project, the view for submitting (meta)data (cockpit) should be displayed

**Comment by AndyDaniel1** [comment]
This issue needs some further refinement

**Comment by AndyDaniel1** [comment]
The notification should be adopted when the SSO is implemented (and replaced with a redirect to the DLP)

**Comment by moellerth** [comment]
Since separating the two views requires greater effort on the technical side, we would suggest integrating the order option directly into the dataprovider view, as discussed. In the mockup, we have illustrated the placement of an additional button in the detail view of a data package. Clicking on this button would open a dialog showing the usual ordering menu including metadata and options. Furthermore, we would place the shopping cart next to the user icon in the header menu at the top right.

Mockup-1: detail view of data package with order option button on right bottom
![platzierung-v2](https://user-images.githubusercontent.com/111288610/203768285-81027817-1040-4709-afc4-5e565d5b169f.png)

Mockup-2: dialog for ordering
![modal-v2](https://user-images.githubusercontent.com/111288610/203768480-ec0577a2-cab5-42c9-9ae7-2a0480424e81.png)

**Comment by AndyDaniel1** [comment]
We have discussed this solution and it should be implemented as an interim solution. In the long term, however, the variant presented above should be kept in mind and taken into account at the latest when the client is re-implemented.

**Comment by moellerth** [comment]
As briefly discussed via slack: 

- ordering should also be implemented for analysis packages
- hidden versions of projects should not be available for ordering

**Comment by AndyDaniel1** [comment]
![grafik](https://user-images.githubusercontent.com/17981185/204766682-9c30ad5f-03b4-4fb8-b3db-f19fb28735c7.png)

**Comment by moellerth** [comment]
Research results related to the non-existent released records on the test system for the dataprovider role

The Problem:
In fact, as a dataprovider, you can actually only see the data that belongs to the projects you are assigned to. Therefore, released data is also not visible if you were not assigned to the project. The problem has nevertheless made it clear, of course, that the display of data for dataproviders needs to be adapted for an optimal flow of the ordering process. Dataproviders need to see assigned project data and additionally released data, even if it is not assigned to them.

The solution:
The ElasticSearch queries created by the SearchHelper and SearchDao classes need to be revised to better distinguish between the different roles. Specifically, the roles will be given the following data view:

- Publisher/Admin: unpublished/hidden packages & released packages (basically everything, current status).
- Dataprovider: unpublished/hidden packages if they are assigned to them (currently) & all released packages
- Users: only concepts, publications & variables (current status)
- Release manager: only concepts & publications (current status)

**Comment by AndyDaniel1** [comment]
@moellerth Thank you very much for the wrap-up and the suggested solution. 

Two supplements: 

The "Release Manager" role should also have access to the same packages as "Publisher" and "Admin" (in fact, the role always comes with at least one of the other two, but conceptually this would be correct).

The "User" role is  useless, so it can stay in its current status. In a revised role concept (developed for SSO), we should think about removing this role for good.

As you continue to work on this issue, please consider that it should lead to a solution like the one described here: https://github.com/dzhw/metadatamanagement/issues/3150#issue-1405806143. The workaround discussed for the time being should no longer be the target: Please get back to me if the effort to implement the solution becomes greater than currently anticipated.

**Comment by moellerth** [comment]
@AndyDaniel1 Following the comment above, I have fixed the following issues so far: 

- order menu is now displayed on the detail page (Did I understand correctly that this was the problem addressed in the comment? I could not notice any deviation of the displayed data packages on the test system when comparing between the order view as dataprovider and the "normal" view as non-logged-in user.)
- Redirection from details page to search page via breadcrumbs was adapted to the currently active view
- the disappeared sidenav menu when editing was reconfigured and is now available again

Let me know if you noticed any further problems.

**Comment by AndyDaniel1** [comment]
@moellerth I just checked this issue again and I think that this issue has not been solved yet, because the list of data packages in the order view still shows only unreleased data packages. It should be the other way around: only released data packages should be displayed in this view. 

> In the "Order Data"-view only the released data packages should be displayed (which can actually be ordered)
> 
> ![grafik](https://user-images.githubusercontent.com/17981185/240608558-3d3df81e-dfcb-4811-8db8-cf36478d288e.png)

**Comment by AndyDaniel1** [comment]
Works well ✔ .
